06 multithreading
igorchupin/JavaLessons pull request #10
Opened 2021-12-08 19:34 UTC by igorchupin

2021-12-09 08:40 UTC, shukal94 requested changes
entity classes should be stored at domain module

2021-12-09 08:40 UTC, shukal94 commented on consoleApp/src/main/java/com/coherentsolutions/chupin/store/consoleapp/readfromconsole/ConsoleReaderSingleton.java
> +                    LOG.log(Level.INFO, "Console reader was created");
just LOG.info should fit

2021-12-09 08:40 UTC, shukal94 commented on consoleApp/src/main/java/com/coherentsolutions/chupin/store/consoleapp/readfromconsole/ReadFromConsole.java
>                  ICommand commandex = FindCommand.findCommand(command);
what is commandex?

2021-12-09 08:40 UTC, shukal94 commented on consoleApp/src/main/java/com/coherentsolutions/chupin/store/consoleapp/readfromconsole/ReadFromConsole.java
>                  } catch (NullPointerException ex) {
remove NPE catch

2021-12-09 08:40 UTC, shukal94 commented on consoleApp/src/main/java/com/coherentsolutions/chupin/store/consoleapp/readfromconsole/ReadFromConsole.java
>                  } catch (NullPointerException ex) {
you can control command instanse via Objects.requireNonNull

2021-12-09 08:40 UTC, shukal94 commented on consoleApp/src/main/java/StoreApp.java
> +        new ClearDaemon().start();
make sure that your thread closes before main thread closes

2021-12-09 08:40 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/AddToCart.java
> +        } catch (InterruptedException ex) {
if interrupted, you can interrupt again

2021-12-09 08:40 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/AddToCart.java
> +        //Thread.currentThread().stop();
remove this

2021-12-09 08:40 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/AddToCart.java
> +        Thread thread = new Thread(new AddToCart("order"), "one");
try to use Runnables class

2021-12-09 08:40 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/ConfirmOrder.java
> +    Cart cart = new Cart();
why is not private?
you are initializing right here, for what?

2021-12-09 08:40 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/ConfirmOrder.java
> +public class ConfirmOrder extends AbstractCommand implements Runnable {
confirm order command should work with Order entity, not with carts

2021-12-09 08:40 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/ConfirmOrder.java
> +        OrderHistory.addToOrderHistory(this.cart);
why static?

2021-12-09 08:40 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/FindCommand.java
> +        AddToCart addToCart = new AddToCart("order");
where is confirm order?

2021-12-09 08:40 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/BookOrder.java
> +public class BookOrder {
is that an action? if so, why is it not a method?

2021-12-09 08:40 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/BookOrder.java
> +        while (result == false);
this logic should be inside the cart

2021-12-09 08:40 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/BookOrder.java
> +        while (result == false);
while(!result)

2021-12-09 08:40 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/BookOrder.java
> +        while (result == false);
do not see the logic of reducing product variable qty

2021-12-09 08:40 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/Cart.java
> +    List<BookOrder> orderList = new LinkedList();
why is it here?

2021-12-09 08:40 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/Cart.java
> +    }
move to another class

2021-12-09 08:40 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/Cart.java
> +            while (!(command).equals("create"));
`} while`

2021-12-09 08:40 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/ClearDaemon.java
> +            LOG.log(Level.INFO, "Order History cleared" + "History size: " + OrderHistory.cartList.size());
after clear the size will be 0

2021-12-09 08:40 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/ClearDaemon.java
> +                sleep(25000);
move to constant

2021-12-09 08:40 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/OrderHistory.java
> +        cartList.clear();
why static?

2021-12-09 08:40 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/products/ProductVariable.java
> +    private static int bookIDGenerator = 0;
generator - should be some class that generates something
use id and generate the value outside of this class

2021-12-09 08:40 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/products/ProductVariable.java
> +    private int bookID;
what purpose of this field?

2021-12-09 08:40 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/products/ProductVariable.java
>      public ProductVariable(ProductType productType, String publisher, BigDecimal price, int left) {
rename `left` to `qty`

2021-12-09 08:40 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/products/ProductVariable.java
> +    public boolean setQuantity (int quantity) {
set should be void
let's do some validation BEFORE

2021-12-10 09:17 UTC, igorchupin commented on consoleApp/src/main/java/com/coherentsolutions/chupin/store/consoleapp/readfromconsole/ConsoleReaderSingleton.java
> +                    LOG.log(Level.INFO, "Console reader was created");
changed

2021-12-10 09:18 UTC, igorchupin commented on consoleApp/src/main/java/com/coherentsolutions/chupin/store/consoleapp/readfromconsole/ReadFromConsole.java
>                  ICommand commandex = FindCommand.findCommand(command);
changed

2021-12-10 09:26 UTC, igorchupin commented on consoleApp/src/main/java/com/coherentsolutions/chupin/store/consoleapp/readfromconsole/ReadFromConsole.java
>                  } catch (NullPointerException ex) {
Changed

2021-12-10 10:29 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/AddToCart.java
> +        //Thread.currentThread().stop();
changed

2021-12-10 10:29 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/AddToCart.java
> +        Thread thread = new Thread(new AddToCart("order"), "one");
changed

2021-12-10 10:30 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/ConfirmOrder.java
> +    Cart cart = new Cart();
changed

2021-12-10 10:30 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/ConfirmOrder.java
> +public class ConfirmOrder extends AbstractCommand implements Runnable {
changed

2021-12-10 10:31 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/ConfirmOrder.java
> +        OrderHistory.addToOrderHistory(this.cart);
changed

2021-12-10 10:34 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/FindCommand.java
> +        AddToCart addToCart = new AddToCart("order");
added

2021-12-10 10:35 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/BookOrder.java
> +public class BookOrder {
changed

2021-12-10 10:35 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/BookOrder.java
> +        while (result == false);
changed

2021-12-10 10:36 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/BookOrder.java
> +        while (result == false);
changed

2021-12-10 10:37 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/Cart.java
> +    List<BookOrder> orderList = new LinkedList();
changed

2021-12-10 10:38 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/Cart.java
> +    }
removed as not needed

2021-12-10 10:39 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/Cart.java
> +            while (!(command).equals("create"));
changed

2021-12-10 10:39 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/ClearDaemon.java
> +            LOG.log(Level.INFO, "Order History cleared" + "History size: " + OrderHistory.cartList.size());
changed

2021-12-10 10:40 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/ClearDaemon.java
> +                sleep(25000);
changed

2021-12-10 10:41 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/OrderHistory.java
> +        cartList.clear();
changed

2021-12-10 10:54 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/products/ProductVariable.java
> +    private static int bookIDGenerator = 0;
changed

2021-12-10 10:55 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/products/ProductVariable.java
> +    private int bookID;
changed

2021-12-10 10:56 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/products/ProductVariable.java
>      public ProductVariable(ProductType productType, String publisher, BigDecimal price, int left) {
changed

2021-12-10 10:56 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/products/ProductVariable.java
> +    public boolean setQuantity (int quantity) {
changed

2021-12-10 15:13 UTC, shukal94 requested changes

2021-12-10 15:13 UTC, shukal94 commented on consoleApp/src/main/java/com/coherentsolutions/chupin/store/consoleapp/readfromconsole/ReadFromConsole.java
> +                result = Objects.requireNonNull(currentCommand.execute());
you can pass the message as the second arg like "No such command"

2021-12-10 15:13 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/orderhistory/OrderHistory.java
> +public class OrderHistory {
still static

2021-12-10 15:13 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/orderhistory/OrderHistory.java
> +        System.out.println("Added: " + order.toString());
do not duplicate the messages

2021-12-10 15:13 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/AddToCart.java
> +        } catch (InterruptedException ex) {
can you join thread init and thread execution?

2021-12-10 15:13 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/AddToCart.java
> +                    "size: " + currentCart.getOrderedBooksList().toString());
add to cart should not submit any order

2021-12-10 15:13 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/CommandQuit.java
> +import com.coherentsolutions.chupin.store.domain.reader.ConsoleReaderSingleton;
may be store module?

2021-12-10 15:13 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/FindCommand.java
> +        ConfirmOrder confirmOrder = new ConfirmOrder("confirm");
let it be submit

2021-12-10 15:13 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/Cart.java
> +package com.coherentsolutions.chupin.store.store.order;
why Cart is in order package? why Cart is not in domain module?

2021-12-10 15:13 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/Cart.java
> +    private double finalCost;
big integer

2021-12-10 15:13 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/Cart.java
> +    private double discount = 0.0;
remove discounts

2021-12-10 15:13 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/Cart.java
> +    private String comment;
also should be removed

ideally cart can have a different types of discounts, payment inof, delivery and billing address but as of now its not required

2021-12-10 15:13 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/Cart.java
> +    public Map<ProductVariable, Integer> addToCartUI() {
move it to a separate class

2021-12-10 15:13 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/Cart.java
> +    public Map<ProductVariable, Integer> findBookAndAddToCart() throws IOException {
see above

2021-12-10 15:13 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/bookidcreator/BookIDCreator.java
> +public class BookIDCreator {
remove this class. in the next task we will use jdbc, and I show you how to resolve generation without any string of code

2021-12-12 08:56 UTC, igorchupin commented on consoleApp/src/main/java/com/coherentsolutions/chupin/store/consoleapp/readfromconsole/ReadFromConsole.java
> +                result = Objects.requireNonNull(currentCommand.execute());
Done

2021-12-12 09:01 UTC, igorchupin commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/orderhistory/OrderHistory.java
> +public class OrderHistory {
Changed to singleton

2021-12-12 09:02 UTC, igorchupin commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/orderhistory/OrderHistory.java
> +        System.out.println("Added: " + order.toString());
Canged

2021-12-12 11:29 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/AddToCart.java
> +                    "size: " + currentCart.getOrderedBooksList().toString());
changed

2021-12-12 11:40 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/CommandQuit.java
> +import com.coherentsolutions.chupin.store.domain.reader.ConsoleReaderSingleton;
it is only a console reader. in my opinion, the best place for it is the console app but we decided to save such essence in domain.

2021-12-12 11:41 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/FindCommand.java
> +        ConfirmOrder confirmOrder = new ConfirmOrder("confirm");
changed

2021-12-12 11:42 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/Cart.java
> +package com.coherentsolutions.chupin.store.store.order;
moved to domain

2021-12-12 12:17 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/Cart.java
> +    private double finalCost;
Changed

2021-12-12 12:18 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/Cart.java
> +    private double discount = 0.0;
changed

2021-12-12 12:27 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/Cart.java
> +    private String comment;
removed

2021-12-12 12:40 UTC, igorchupin commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/bookidcreator/BookIDCreator.java
> +public class BookIDCreator {
removed

2021-12-12 12:50 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/Cart.java
> +    public Map<ProductVariable, Integer> addToCartUI() {
done

2021-12-12 12:51 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/Cart.java
> +    public Map<ProductVariable, Integer> findBookAndAddToCart() throws IOException {
done

2021-12-13 15:13 UTC, shukal94 requested changes

2021-12-13 15:13 UTC, shukal94 commented on domain/pom.xml
> +        <version>2.12.0</version>
let's update it to 2.15.0 :)

2021-12-13 15:13 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/AddToCart.java
> +                }
while creating the store - let's instantiate cart object as well

2021-12-13 15:13 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/AddToCart.java
> +                myStore.setCurrentCart(currentCart); }
what is that?

2021-12-13 15:13 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/cart/CartUI.java
> +                        LOG.log(Level.INFO, "Command *save* Order List size: " + cart.getOrderedBooksList().size());
you're doing nothing to save, just print - remove this block

2021-12-13 15:13 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/cart/Cart.java
> +    private Map<ProductVariable, Integer> orderedBooksList = new HashMap<>();
why have you initialized there? you have constructor

2021-12-13 15:13 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/cart/Cart.java
> +public class Cart {
should be splitted into 2 classes - cart and cartUI

2021-12-13 15:13 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/cart/CartUI.java
> +public class CartUI {
why is in domain?

2021-12-13 15:13 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/AddToCart.java
> +        Thread thread = new Thread(runnable); */
how about to remove dead code?

2021-12-13 15:13 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/FindCommand.java
> +        ConfirmOrder confirmOrder = new ConfirmOrder("submit");
submit or confirm?

2021-12-13 15:13 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/ClearOrderHistoryDaemon.java
> +    private static final int SLEEP_TIME = 25000;
25000 of what?

2021-12-13 15:13 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/Order.java
> +public class Order {
why is it in store?

2021-12-13 15:13 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/Order.java
> +        System.out.println("Your order was successfully created.");
this is domain class, so remove all the user interaction

2021-12-13 15:13 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/products/Product.java
>  public class Product {
see above

2021-12-13 15:13 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/storecreation/Store.java
> +    public static void printStore() {
why  static?

2021-12-13 15:35 UTC, igorchupin commented on domain/pom.xml
> +        <version>2.12.0</version>
done

2021-12-13 15:39 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/AddToCart.java
> +                }
done

2021-12-13 17:25 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/AddToCart.java
> +                myStore.setCurrentCart(currentCart); }
removed

2021-12-13 17:58 UTC, igorchupin commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/cart/CartUI.java
> +                        LOG.log(Level.INFO, "Command *save* Order List size: " + cart.getOrderedBooksList().size());
removed

2021-12-13 18:00 UTC, igorchupin commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/cart/Cart.java
> +    private Map<ProductVariable, Integer> orderedBooksList = new HashMap<>();
Moved to constructor

2021-12-13 18:06 UTC, igorchupin commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/cart/Cart.java
> +public class Cart {
changed

2021-12-13 18:07 UTC, igorchupin commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/cart/CartUI.java
> +public class CartUI {
Moved to console app

2021-12-13 18:10 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/FindCommand.java
> +        ConfirmOrder confirmOrder = new ConfirmOrder("submit");
changed

2021-12-13 18:15 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/ClearOrderHistoryDaemon.java
> +    private static final int SLEEP_TIME = 25000;
Name was changed

2021-12-13 18:18 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/FindCommand.java
> +        ConfirmOrder confirmOrder = new ConfirmOrder("submit");
![image](https://user-images.githubusercontent.com/78274609/145866555-4de175d3-1122-4dda-94a0-98e31b87980d.png)
Now I do not know.

2021-12-13 18:21 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/Order.java
> +public class Order {
moved to domain

2021-12-13 18:22 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/order/Order.java
> +        System.out.println("Your order was successfully created.");
removed

2021-12-13 18:25 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/products/Product.java
>  public class Product {
changed

2021-12-13 18:28 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/storecreation/Store.java
> +    public static void printStore() {
changed

2021-12-14 10:31 UTC, shukal94 requested changes

2021-12-14 10:31 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/order/Order.java
> +    private final BigDecimal finalCost;
let's have Cart instance as class field, then update all the related logic

2021-12-14 10:31 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/CommandQuit.java
> +import com.coherentsolutions.chupin.store.domain.reader.ConsoleReaderSingleton;
domain module should have only domain entites, nothing more. Commands are part of executing logic, so they are should be in store module

2021-12-14 10:31 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/FindCommand.java
> +        ConfirmOrder confirmOrder = new ConfirmOrder("confirm");
where?

2021-12-14 10:31 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/products/Product.java
>  public class Product {
where?

2021-12-14 10:31 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/products/ProductVariable.java
> +    private int bookID;
maybe long?

2021-12-14 11:02 UTC, igorchupin commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/order/Order.java
> +    private final BigDecimal finalCost;
Changed

2021-12-14 11:04 UTC, igorchupin commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/order/Order.java
> +    private final BigDecimal finalCost;
Changed

2021-12-14 11:19 UTC, shukal94 approved these changes

2021-12-14 11:37 UTC, merged