07 db
igorchupin/JavaLessons pull request #11
Opened 2021-12-16 16:33 UTC by igorchupin

2021-12-17 09:57 UTC, shukal94 requested changes
will review your schema a bit later

2021-12-17 09:57 UTC, shukal94 commented on consoleApp/src/main/java/StoreApp.java
> +import com.coherentsolutions.chupin.store.domain.dbtools.CreateDeleteTables;
why is this in domain?

2021-12-17 09:57 UTC, shukal94 commented on consoleApp/src/main/java/StoreApp.java
> +import com.coherentsolutions.chupin.store.domain.dbtools.CreateDeleteTables;
do not see any usages of those imports. remove them

2021-12-17 09:57 UTC, shukal94 commented on consoleApp/src/main/java/com/coherentsolutions/chupin/store/consoleapp/readfromconsoleui/CartUI.java
>          int bookID = Integer.parseInt(scanner.readLine());
why should you put id?
you can delegate this responsibility to db which could do it better than you

2021-12-17 09:57 UTC, shukal94 commented on consoleApp/src/main/java/com/coherentsolutions/chupin/store/consoleapp/readfromconsoleui/CartUI.java
> +                //TODO
todo what?

2021-12-17 09:57 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dao/CategoryDao.java
> +    }
implement those methods in right way

2021-12-17 09:57 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dao/CategoryDao.java
> +    public boolean create(Category category) {
let's return a created instance of category instead of bool

2021-12-17 09:57 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dao/CategoryDao.java
> +            String request = "INSERT INTO Category VALUES (null, ?)";
what is null?

2021-12-17 09:57 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dao/IDAO.java
> +    public abstract boolean create(T object);
why is this abstract?

2021-12-17 09:57 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dao/IDAO.java
> +    boolean updateByObject(T object);
let it be T

2021-12-17 09:57 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dao/IDAO.java
> +    boolean delete(T object);
can be void

2021-12-17 09:57 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dao/OrderHistoryDAO.java
> +        String requestOrderedBook = "INSERT INTO OrderedBooks VALUES (null, ?, ?, ?, ?, ?, ?, ?, ?)";
why null?

2021-12-17 09:57 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dao/OrderHistoryDAO.java
> +        String request2 = "Delete from  orderhistory;";
make these names more understandable

2021-12-17 09:57 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dao/OrderHistoryDAO.java
> +    }
implement them

2021-12-17 09:57 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dao/ProductDao.java
> +public class ProductDao implements IDAO<Product> {
where it should be instantiated?

2021-12-17 09:57 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dao/ProductDao.java
> +    }
implement them

2021-12-17 09:57 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dao/ProductDao.java
> +    public boolean create(Product product) {
why null?

2021-12-17 09:57 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dao/ProductVariableDao.java
> +public class ProductVariableDao implements IDAO<ProductVariable> {
see above

2021-12-17 09:57 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dao/SubCategoryDao.java
> +package com.coherentsolutions.chupin.store.domain.dao;
see dao comments

2021-12-17 09:57 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dbtools/ConnectionToDB.java
> +    public static final String PASS = "password";
do not store the creds and urls in the code. use `.properties` file and of course you will need properties reader

2021-12-17 09:57 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dbtools/ConnectionToDB.java
> +    }
just curious: how it feels with threads?

2021-12-17 09:57 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dbtools/store_db (creeation).sql
> +SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
name: do not leave spaces in the filenames. ever.
also, why is this in domain pkg?
place this in resources folder

2021-12-17 09:57 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dbtools/CreateDeleteTables.java
> +            statement.execute(deleteAllTables);
why do we need this class if we have sql script?

2021-12-17 09:57 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/order/Order.java
> +    public Map<ProductVariable, Integer> getOrderedBooks() {
for what?

2021-12-17 09:57 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/order/Order.java
> +    public Map<ProductVariable, Integer> getOrderedBooks() {
cart should already have this

2021-12-17 09:57 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/products/Category.java
> +    private long categoryID;
use Long.class

2021-12-17 09:57 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/products/Product.java
> +    public long subCategoryID;
why should we need this?

2021-12-17 09:57 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/products/SubCategory.java
> +    long categoryID;
why do we need this?

2021-12-17 09:57 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/storecreation/RandomStorePopulator.java
>      static CopyOnWriteArrayList<ProductVariable> productVariables;
remove this class at all

2021-12-18 13:17 UTC, igorchupin commented on consoleApp/src/main/java/StoreApp.java
> +import com.coherentsolutions.chupin.store.domain.dbtools.CreateDeleteTables;
removed

2021-12-18 13:17 UTC, igorchupin commented on consoleApp/src/main/java/com/coherentsolutions/chupin/store/consoleapp/readfromconsoleui/CartUI.java
> +                //TODO
Removed

2021-12-18 13:53 UTC, igorchupin commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dao/CategoryDao.java
> +    }
These methods will be never used. Now they will throw MethodNotImplementedException

2021-12-18 14:35 UTC, igorchupin commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dao/CategoryDao.java
> +    public boolean create(Category category) {
changed

2021-12-18 15:20 UTC, igorchupin commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dao/CategoryDao.java
> +            String request = "INSERT INTO Category VALUES (null, ?)";
Changed

2021-12-18 15:21 UTC, igorchupin commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dao/IDAO.java
> +    public abstract boolean create(T object);
changed

2021-12-18 15:27 UTC, igorchupin commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dao/IDAO.java
> +    boolean updateByObject(T object);
now it returns T

2021-12-18 15:28 UTC, igorchupin commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dao/IDAO.java
> +    boolean delete(T object);
changed

2021-12-18 15:28 UTC, igorchupin commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dao/OrderHistoryDAO.java
> +        String requestOrderedBook = "INSERT INTO OrderedBooks VALUES (null, ?, ?, ?, ?, ?, ?, ?, ?)";
changed

2021-12-18 15:29 UTC, igorchupin commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dao/OrderHistoryDAO.java
> +        String request2 = "Delete from  orderhistory;";
changed

2021-12-18 15:30 UTC, igorchupin commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dao/OrderHistoryDAO.java
> +    }
they will be never used

2021-12-18 15:52 UTC, igorchupin commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dao/ProductDao.java
> +    }
they will be never used

2021-12-18 15:52 UTC, igorchupin commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dao/ProductDao.java
> +    public boolean create(Product product) {
changed

2021-12-18 15:52 UTC, igorchupin commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dbtools/ConnectionToDB.java
> +    public static final String PASS = "password";
changed

2021-12-18 15:52 UTC, igorchupin commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dbtools/store_db (creeation).sql
> +SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
changed

2021-12-18 15:53 UTC, igorchupin commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/dbtools/CreateDeleteTables.java
> +            statement.execute(deleteAllTables);
removed

2021-12-18 15:56 UTC, igorchupin commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/products/Category.java
> +    private long categoryID;
changed

2021-12-18 15:57 UTC, igorchupin commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/products/Product.java
> +    public long subCategoryID;
changed

2021-12-18 15:57 UTC, igorchupin commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/products/SubCategory.java
> +    long categoryID;
changed

2021-12-18 15:58 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/storecreation/RandomStorePopulator.java
>      static CopyOnWriteArrayList<ProductVariable> productVariables;
removed

2021-12-20 07:54 UTC, shukal94 requested changes

2021-12-20 07:54 UTC, shukal94 commented on consoleApp/src/main/java/StoreApp.java
> +        //new ClearOrderHistoryDaemon().start();
are you going to use this daemon?

2021-12-20 07:54 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/order/Order.java
> +    private final Cart ORDER_CART;
it is not a constant, why in uppercase?

2021-12-20 07:54 UTC, shukal94 commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/storesingleton/Store.java
>      public void printStore() {
move to another class

2021-12-20 07:54 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/dao/CategoryDao.java
> +        throw new MethodNotImplementedException();
please specify which method is not implemented in exception message

2021-12-20 07:54 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/dbtools/PropertiesReader.java
> +    private static final String pathToFile = "store/src/main/resources/db_properties.json";
let's use `.properties` file, json is too much for that

2021-12-20 09:03 UTC, igorchupin commented on consoleApp/src/main/java/StoreApp.java
> +        //new ClearOrderHistoryDaemon().start();
Changed

2021-12-20 09:04 UTC, igorchupin commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/order/Order.java
> +    private final Cart ORDER_CART;
changed

2021-12-20 09:07 UTC, igorchupin commented on domain/src/main/java/com/coherentsolutions/chupin/store/domain/storesingleton/Store.java
>      public void printStore() {
changed

2021-12-20 09:07 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/dbtools/PropertiesReader.java
> +    private static final String pathToFile = "store/src/main/resources/db_properties.json";
changed

2021-12-20 09:23 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/dao/CategoryDao.java
> +        throw new MethodNotImplementedException();
changed

2021-12-20 19:26 UTC, shukal94 requested changes
some minor comments

2021-12-20 19:26 UTC, shukal94 commented on consoleApp/src/main/java/com/coherentsolutions/chupin/store/consoleapp/readfromconsoleui/CartUI.java
> +    public static void printStore() {
why is it in cart ui?

2021-12-20 19:26 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/AddToCart.java
> +                    Store.getStoreInstance().setCurrentCart(cart);
you can use myStore var

2021-12-20 19:26 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/ConfirmOrder.java
> +            if (Store.getStoreInstance().getCurrentCart() == null) {
are you sure this condition is reachable?

2021-12-21 07:55 UTC, igorchupin commented on consoleApp/src/main/java/com/coherentsolutions/chupin/store/consoleapp/readfromconsoleui/CartUI.java
> +    public static void printStore() {
a command was created

2021-12-21 07:56 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/AddToCart.java
> +                    Store.getStoreInstance().setCurrentCart(cart);
changed

2021-12-21 08:36 UTC, shukal94 approved these changes

2021-12-21 08:44 UTC, merged