08 http
igorchupin/JavaLessons pull request #12
Opened 2021-12-23 07:27 UTC by igorchupin

2021-12-23 08:45 UTC, shukal94 requested changes

2021-12-23 08:45 UTC, shukal94 commented on consoleApp/src/main/java/StoreApp.java
> +        Server.createAndStartServer();
follow single responsibiltiy.
create server, then start it. btw, why static?
where the props to init the server

2021-12-23 08:45 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/CommandQuit.java
> +            Server.stopServer();
same as for start server

2021-12-23 08:45 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/dao/OrderDAO.java
> +    public OrderTransfer getByID(long id) throws MethodNotImplementedException {
I thought you are going to make another layer of transfer classes instead of replacing

2021-12-23 08:45 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/dto/ProductVariableDTO.java
> +                '}';
you can use Jackson object mapper to serialize/deserialize instead of toString. actually never seen toString usage except logging

2021-12-23 08:45 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/dto/ProductVariableDTO.java
> +                '}';
or Gson

2021-12-23 08:45 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/httpadaptes/AddToCartAdapter.java
> +        Gson gson = new Gson();
let's generify Gson serializer in the another class

2021-12-23 08:45 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/httpadaptes/AllVariablesAdapter.java
> +                        get("http://localhost:8010/variables").body().asString();
we can hardcode creds for now but why to hardcode host and port?

2021-12-23 08:45 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/httpadaptes/ClearHistoryAdapter.java
> +    public void getRequest() {
delete maybe?

2021-12-23 08:45 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/objecttransfers/ProductVariableFromJson.java
> +
remove these blank lines

2021-12-23 08:45 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/objecttransfers/ProductVariablesTransfer.java
> +        GsonBuilder builder = new GsonBuilder();
lets move this to another class

2021-12-23 18:03 UTC, igorchupin commented on consoleApp/src/main/java/StoreApp.java
> +        Server.createAndStartServer();
Changed to singleton

2021-12-23 18:03 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/CommandQuit.java
> +            Server.stopServer();
changed

2021-12-23 18:04 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/dao/OrderDAO.java
> +    public OrderTransfer getByID(long id) throws MethodNotImplementedException {
The application uses "objecttransfers" package (a new layer), the server uses "dao" package

2021-12-23 18:05 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/dto/ProductVariableDTO.java
> +                '}';
"To String" was deleted as not in use

2021-12-23 18:05 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/httpadaptes/AddToCartAdapter.java
> +        Gson gson = new Gson();
Changed

2021-12-23 18:05 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/httpadaptes/AllVariablesAdapter.java
> +                        get("http://localhost:8010/variables").body().asString();
changed

2021-12-23 18:06 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/httpadaptes/ClearHistoryAdapter.java
> +    public void getRequest() {
changed

2021-12-23 18:07 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/objecttransfers/ProductVariableFromJson.java
> +
changed

2021-12-23 18:07 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/objecttransfers/ProductVariablesTransfer.java
> +        GsonBuilder builder = new GsonBuilder();
removed as not in use

2021-12-24 09:54 UTC, shukal94 requested changes

2021-12-24 09:54 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/CommandQuit.java
>              ConsoleReaderSingleton.closeReader();
are you going to stop this?

2021-12-24 09:54 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/commands/CommandQuit.java
>              ConsoleReaderSingleton.closeReader();
server I mean

2021-12-24 09:54 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/httpadaptes/ConfirmOrderAdapter.java
> +        String requestBody = generalParser.deserialize(orderTransfer);
serialize - convert object to json string
deserialize - convert json string to object

2021-12-24 09:54 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/objecttransfers/GeneralParser.java
> +    }
replace the names

2021-12-24 09:54 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/objecttransfers/GeneralParser.java
> +    }
those methods could be static

2021-12-24 09:54 UTC, shukal94 commented on store/src/main/resources/server_properties.properties
> +url=http://localhost:
rename this to host, remove `:`

2021-12-24 09:54 UTC, shukal94 commented on store/src/main/java/com/coherentsolutions/chupin/store/store/server/Server.java
> +        System.out.println("Server was started");
how about to use logger?

2021-12-24 10:02 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/httpadaptes/ConfirmOrderAdapter.java
> +        String requestBody = generalParser.deserialize(orderTransfer);
changed

2021-12-24 10:20 UTC, igorchupin commented on store/src/main/java/com/coherentsolutions/chupin/store/store/server/Server.java
> +        System.out.println("Server was started");
added

2021-12-24 10:22 UTC, igorchupin commented on store/src/main/resources/server_properties.properties
> +url=http://localhost:
changed

2021-12-24 11:02 UTC, shukal94 approved these changes

2021-12-24 11:34 UTC, merged