03 more
igorchupin/JavaLessons pull request #5
Opened 2021-10-31 10:53 UTC by igorchupin

One more idea

2021-11-01 15:25 UTC, shukal94 requested changes

2021-11-01 15:25 UTC, shukal94 commented on store/src/main/java/ProductVariable.java
> +    private String coverID;
remove duplicates

2021-11-01 15:25 UTC, shukal94 commented on store/src/main/java/ProductVariable.java
> +        }
useless

2021-11-01 15:25 UTC, shukal94 commented on store/src/main/java/RandomStorePopulator.java
> +
remove blank lines

2021-11-02 07:57 UTC, shukal94 requested changes

2021-11-02 07:57 UTC, shukal94 commented on store/src/main/java/ProductVariable.java
> +    CoversTypes coverTypes;
coverType

2021-11-02 07:57 UTC, shukal94 commented on store/src/main/java/ProductVariable.java
> +    private final int exemplarsLeft;
quantity

2021-11-02 07:57 UTC, shukal94 commented on store/src/main/java/ProductVariable.java
> +    private final double price;
use BigDecimal for money

2021-11-02 07:57 UTC, shukal94 commented on store/src/main/java/ProductVariable.java
> +    public String printVariable() {
this is toString responsibility, please rename that

2021-11-02 17:13 UTC, igorchupin commented on store/src/main/java/ProductVariable.java
> +    private String coverID;
Removed all about ID

2021-11-02 17:13 UTC, igorchupin commented on store/src/main/java/ProductVariable.java
> +        }
Removed

2021-11-02 17:14 UTC, igorchupin commented on store/src/main/java/RandomStorePopulator.java
> +
Removed

2021-11-02 17:15 UTC, igorchupin commented on store/src/main/java/ProductVariable.java
> +    CoversTypes coverTypes;
Changed

2021-11-02 17:15 UTC, igorchupin commented on store/src/main/java/ProductVariable.java
> +    private final int exemplarsLeft;
Changed

2021-11-02 17:21 UTC, igorchupin commented on store/src/main/java/ProductVariable.java
> +    private final double price;
Changed

2021-11-02 17:23 UTC, igorchupin commented on store/src/main/java/ProductVariable.java
> +    public String printVariable() {
Changed

2021-11-03 07:49 UTC, shukal94 approved these changes

2021-11-07 09:32 UTC, merged