03 02 methods and oop
igorchupin/JavaLessons pull request #7
Opened 2021-11-07 15:38 UTC by igorchupin

1) Now Product Variable inherits the Product and contains fields Rate and Name.

2) Now Methods from "StoreApp" (print store) were moved to the corresponding classes (ProductVariable, Store)

2021-11-08 12:31 UTC, shukal94 requested changes

2021-11-08 12:31 UTC, shukal94 commented on store/src/main/java/Product.java
> +    String name;
why did you remove private fields?

2021-11-08 12:31 UTC, shukal94 commented on store/src/main/java/Product.java
> +        this.rate = rate;
if you want to have an additional constructor let's init productVariables as an empty list

2021-11-08 12:31 UTC, shukal94 commented on store/src/main/java/Product.java
> +        return this.name;
you don't need this here

2021-11-08 12:31 UTC, shukal94 commented on store/src/main/java/Product.java
> +        return "Product name: " + this.getName() + "; product rate: " + this.getRate() + "; contains " + this.productVariablesList.size() + " variables";
see comments above about Category class

2021-11-08 12:31 UTC, shukal94 commented on store/src/main/java/ProductVariable.java
> +public class ProductVariable extends Product implements Comparable<ProductVariable> {
why do we need to extend Product?

2021-11-08 12:31 UTC, shukal94 commented on store/src/main/java/ProductVariable.java
> +    public ProductVariable(String name, Integer rate, String publisher, CoversTypes types, BigDecimal price, int left) {
different variations may have different rate, or all the variations have one rate
in the second case you don't need to inherit from Product
in the first case you can iniе rate field here

2021-11-08 12:31 UTC, shukal94 commented on store/src/main/java/ProductVariable.java
> +    static ArrayList<ProductVariable> listAllVariables = new ArrayList<>();
why do you need variable list in variable class?

2021-11-08 12:31 UTC, shukal94 commented on store/src/main/java/ProductVariable.java
> +    private int quantity = 0;
remove init

2021-11-08 12:31 UTC, shukal94 commented on store/src/main/java/ProductVariable.java
> +        if (this.price.doubleValue() == variableProduct.price.doubleValue()) {
why don't you use equals from BigDecimal.class?

2021-11-08 12:31 UTC, shukal94 commented on store/src/main/java/ProductVariable.java
> +        }
please follow single-responsibility principle: remove those methods

2021-11-08 12:31 UTC, shukal94 commented on store/src/main/java/Store.java
> +    }
I think there's no need to override those methods here

2021-11-08 12:31 UTC, shukal94 commented on store/src/main/java/SubCategory.java
> +        return "Subcategory name: " + this.getName() + "; Contains " + this.getProductList().size() + " products";
see the comments for Product

2021-11-08 14:22 UTC, igorchupin commented on store/src/main/java/Category.java
> +    private String name = "";
removed

2021-11-08 18:02 UTC, igorchupin commented on store/src/main/java/Category.java
> +        return "Category name: " + this.getName() + "; Contains " + this.getSubcategoryList().size() + " subcategories";
This was changed

2021-11-08 18:05 UTC, igorchupin commented on store/src/main/java/Product.java
> +    String name;
Changed

2021-11-08 18:06 UTC, igorchupin commented on store/src/main/java/Product.java
> +        this.rate = rate;
Constructor was removed

2021-11-08 18:07 UTC, igorchupin commented on store/src/main/java/Product.java
> +        return this.name;
This was changed

2021-11-08 18:11 UTC, igorchupin commented on store/src/main/java/Product.java
> +        return "Product name: " + this.getName() + "; product rate: " + this.getRate() + "; contains " + this.productVariablesList.size() + " variables";
Changed "toString"

2021-11-08 18:11 UTC, igorchupin commented on store/src/main/java/ProductVariable.java
> +public class ProductVariable extends Product implements Comparable<ProductVariable> {
This was removed

2021-11-08 18:13 UTC, igorchupin commented on store/src/main/java/ProductVariable.java
> +    public ProductVariable(String name, Integer rate, String publisher, CoversTypes types, BigDecimal price, int left) {
all the variations have one rate. Fields "rate" and "name" were added.

2021-11-08 18:13 UTC, igorchupin commented on store/src/main/java/ProductVariable.java
> +    static ArrayList<ProductVariable> listAllVariables = new ArrayList<>();
We do not need it. I removed it to the "Utils" class

2021-11-08 18:18 UTC, igorchupin commented on store/src/main/java/ProductVariable.java
> +    private int quantity = 0;
removed

2021-11-08 18:21 UTC, igorchupin commented on store/src/main/java/ProductVariable.java
> +        if (this.price.doubleValue() == variableProduct.price.doubleValue()) {
Changed to (this.price.equals(variableProduct.price))

2021-11-08 18:21 UTC, igorchupin commented on store/src/main/java/ProductVariable.java
> +        }
Moved to the Utils class

2021-11-08 18:24 UTC, igorchupin commented on store/src/main/java/Store.java
> +    }
they were removed

2021-11-09 14:19 UTC, shukal94 approved these changes

2021-11-09 17:20 UTC, merged