05 patterns
igorchupin/JavaLessons pull request #9
Opened 2021-11-25 10:54 UTC by igorchupin

Strategy was added for reading command (from file/ from console)
Command was added for commands execution
Singleton was added for the Store class

2021-11-26 14:57 UTC, shukal94 requested changes
you have groupId in your poms, let's place your classes correspondingly by module and package

2021-11-26 14:57 UTC, shukal94 commented on store/src/main/java/CommandError.java
> +        System.out.println("No such command");
let's throw some custom exception there

2021-11-26 14:57 UTC, shukal94 commented on store/src/main/java/CommandHistory.java
> +    private static final Stack<CommandAbstract> history = new Stack<>();
use ArrayDequeue, Stack is deprecated

2021-11-26 14:57 UTC, shukal94 commented on store/src/main/java/CommandHistory.java
> +        } catch (NullPointerException ex) {
let's have `Objects.requireNonNull(c, "Command should not be null!")`

2021-11-26 14:57 UTC, shukal94 commented on store/src/main/java/CommandHistory.java
> +    public static void Printlog() {
please follow java style conventions

2021-11-26 14:57 UTC, shukal94 commented on store/src/main/java/CommandHistory.java
> +                System.out.println(history.get(i).toString());
use logger and see the comment above regarding npe

2021-11-26 14:57 UTC, shukal94 commented on store/src/main/java/CommandAbstract.java
> +public abstract class CommandAbstract {
let it be an interface Command

2021-11-26 14:57 UTC, shukal94 commented on store/src/main/java/CommandQuit.java
> +        System.exit(0);
bad practise: just return true or false
also now return false is unreachable

2021-11-26 14:57 UTC, shukal94 commented on store/src/main/java/CommandSort.java
> +    static ArrayList<ProductVariable> listAllVariables = new ArrayList<>();
why static?

2021-11-26 14:57 UTC, shukal94 commented on store/src/main/java/CommandSort.java
> +            File xmlFile = new File("store/src/main/resources/config.xml");
move filename to constant

2021-11-26 14:57 UTC, shukal94 commented on store/src/main/java/CommandSort.java
> +            }
it easier to work with jaxb unmarshaller

2021-11-26 14:57 UTC, shukal94 commented on store/src/main/java/CommandError.java
> +    public boolean execute() {
also let's return Object there - in implementations we can return various objects, lists, etc.

2021-11-26 14:57 UTC, shukal94 commented on store/src/main/java/ReadFromConsoleStrategy.java
> +            Utils.findAndRunCommand(command);
which Utils?

2021-11-26 14:57 UTC, shukal94 commented on store/src/main/java/ReadFromConsoleStrategy.java
> +
mark as override

2021-11-26 14:57 UTC, shukal94 commented on store/src/main/java/ReadFromConsoleStrategy.java
> +    public void runCommand() {
why command does not return anything?

2021-11-27 09:25 UTC, igorchupin commented on store/src/main/java/CommandError.java
> +        System.out.println("No such command");
Now it throws a custom exception

2021-11-27 09:33 UTC, igorchupin commented on store/src/main/java/CommandHistory.java
> +    private static final Stack<CommandAbstract> history = new Stack<>();
Now it uses ArrayDequeue

2021-11-27 09:40 UTC, igorchupin commented on store/src/main/java/CommandHistory.java
> +        } catch (NullPointerException ex) {
This was changed

2021-11-27 09:41 UTC, igorchupin commented on store/src/main/java/CommandHistory.java
> +    public static void Printlog() {
Name was changed

2021-11-27 11:18 UTC, igorchupin commented on store/src/main/java/CommandHistory.java
> +                System.out.println(history.get(i).toString());
The method was deleted. Now it logs commands into the file using log4j.

2021-11-27 12:53 UTC, igorchupin commented on store/src/main/java/CommandAbstract.java
> +public abstract class CommandAbstract {
This was changed

2021-11-27 13:07 UTC, igorchupin commented on store/src/main/java/CommandQuit.java
> +        System.exit(0);
Now it returns "Finished" because it does not make sense to return anything because the program had been ended.

2021-11-27 13:16 UTC, igorchupin commented on store/src/main/java/CommandSort.java
> +    static ArrayList<ProductVariable> listAllVariables = new ArrayList<>();
This was changed

2021-11-27 13:17 UTC, igorchupin commented on store/src/main/java/CommandSort.java
> +            File xmlFile = new File("store/src/main/resources/config.xml");
This was changed

2021-11-27 15:03 UTC, igorchupin commented on store/src/main/java/CommandError.java
> +    public boolean execute() {
This was changed

2021-11-27 15:14 UTC, igorchupin commented on store/src/main/java/ReadFromConsoleStrategy.java
> +            Utils.findAndRunCommand(command);
Methods were moved to the corresponding Interfaces

2021-11-27 15:20 UTC, igorchupin commented on store/src/main/java/ReadFromConsoleStrategy.java
> +
This was changed

2021-11-27 19:43 UTC, igorchupin commented on store/src/main/java/CommandSort.java
> +            }
@shukal94 I tried jaxb unmarshaller. Now I can create simple objects from XML and write objects to XML. But I have no idea how to create an object if we can not know the fields name and count of fields (according to the requirements XML file can contain n different combinations of comparators + values. The easiest way was to create a Map.

There is what I tried to do with jaxb:
 
`import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class Marsh {

        String filePath = "store/src/main/resources/configMarsh.xml";
        File file = new File(filePath);
        
        public void printcommands () throws JAXBException, IOException, JAXBException {
            Sort ss = new Sort();
            ss.setName("price");
            ss.setValue("desc");

            
            JAXBContext jaxbContext = JAXBContext.newInstance( Sort.class );
            Marshaller jaxbMarshaller = jaxbContext.createMarshaller();
            ((Marshaller) jaxbMarshaller).setProperty( Marshaller.JAXB_FORMATTED_OUTPUT, true );
            jaxbMarshaller.marshal(ss, file );
        }
    }


    @XmlType( propOrder = {"name", "value" } )
    @XmlRootElement( name = "sort" )

    class Sort {
        String name;
        String value;

        @XmlElement(name = "name")
        public void setName(String name) {
            this.name = name;
        }

        @XmlElement(name = "value")
        public void setValue(String value) {
            this.value = value;
        }

        public String getName() {
            return name;
        }

        public String getValue() {
            return value;
        }
    }`

2021-11-27 19:45 UTC, igorchupin commented on store/src/main/java/ReadFromConsoleStrategy.java
> +    public void runCommand() {
Now all commands return an object (some commands return List, some return Array list, some return Object)

2021-11-29 14:33 UTC, shukal94 requested changes
classes are still donot have packages

2021-11-29 14:33 UTC, shukal94 commented on consoleApp/src/main/java/CommandError.java
> +public class CommandError implements ICommand {
why do we need error as command?

2021-11-29 14:33 UTC, shukal94 commented on consoleApp/src/main/java/CommandHistory.java
> +        Logger log = LogManager.getLogger("logger");
define logger as private static constant on class level, and pass the current class name as constructor param - then you will know where logger was invoked

2021-11-29 14:33 UTC, shukal94 commented on consoleApp/src/main/java/CommandQuit.java
> +        return "Finished"; //Does not make sense to return anything because the program had been ended
so do not call exit :)

2021-11-29 14:33 UTC, shukal94 commented on consoleApp/src/main/java/CommandSort.java
> +    }
why static and hard link to array list?

2021-11-29 14:33 UTC, shukal94 commented on consoleApp/src/main/java/CommandTop.java
> +    List<ProductVariable> result;
they are package-private, why?

2021-11-29 14:33 UTC, shukal94 commented on consoleApp/src/main/java/CommandTop.java
> +        System.out.println(listAllVariables.subList(0, 5).toString() + "\n");
use logger

2021-11-29 14:33 UTC, shukal94 commented on consoleApp/src/main/java/ICommand.java
> +    }
move to another class

2021-11-29 14:33 UTC, shukal94 commented on consoleApp/src/main/java/Marsh.java
> +            jaxbMarshaller.marshal(compar, file ); */
remove dead code

2021-11-29 14:33 UTC, shukal94 commented on consoleApp/src/main/java/Marsh.java
> +    public class Marsh {
use formatter

2021-11-29 14:33 UTC, shukal94 commented on consoleApp/src/main/java/Marsh.java
> +    public class Marsh {
what does it mean?

2021-11-29 14:33 UTC, shukal94 commented on consoleApp/src/main/java/Marsh.java
> +        }
move to another classes

2021-11-29 14:33 UTC, shukal94 commented on consoleApp/src/main/resources/logs.log
> +2021-11-27 14:21:54,957 INFO logger [main]  Command was executed: CommandError@2c1b9e4b
ignore this

2021-11-29 14:33 UTC, shukal94 commented on logs/log4j2.log
> +2021-11-27 14:07:46,750 INFO logger [main] 2021-11-27T14:07:46.750915900 Command was executed: CommandError@4fe89c24
and this too

2021-11-29 14:33 UTC, shukal94 commented on store/pom.xml
> +        </dependency>
why do we need this dependency?

2021-11-29 14:33 UTC, shukal94 commented on store/src/main/java/ProductVariable.java
> +        final ArrayList<Comparator> comparatorsList = CommandSort.createComparatorsList();
why should this class have to know about commands?

2021-11-29 14:33 UTC, shukal94 commented on store/src/main/resources/configMarsh1.xml
> +</comparators>
wrap this to a sort object

2021-11-30 08:09 UTC, igorchupin commented on store/src/main/java/CommandSort.java
> +            }
Now it works with jaxb unmarshaller

2021-11-30 09:03 UTC, igorchupin commented on consoleApp/src/main/java/CommandError.java
> +public class CommandError implements ICommand {
Now its a separate class, not command

2021-11-30 09:24 UTC, igorchupin commented on consoleApp/src/main/java/CommandHistory.java
> +        Logger log = LogManager.getLogger("logger");
This was changed

2021-11-30 10:06 UTC, igorchupin commented on consoleApp/src/main/java/CommandQuit.java
> +        return "Finished"; //Does not make sense to return anything because the program had been ended
This was changed. Now it closes the reader.

2021-11-30 10:21 UTC, igorchupin commented on consoleApp/src/main/java/CommandSort.java
> +    }
This was moved to a separate class.

2021-11-30 10:23 UTC, igorchupin commented on consoleApp/src/main/java/CommandTop.java
> +    List<ProductVariable> result;
Now they are private

2021-11-30 10:26 UTC, shukal94 requested changes

2021-11-30 10:26 UTC, shukal94 commented on consoleApp/src/main/java/ICommand.java
> +                    exCommand = new CommandError();
throw an exception there

2021-11-30 10:26 UTC, shukal94 commented on consoleApp/src/main/java/Marsh.java
> +    public class Marsh {
update to meaningful name

2021-11-30 10:26 UTC, shukal94 commented on consoleApp/src/main/java/ReadFromConsoleStrategy.java
> +                try {
use formatter

2021-11-30 10:26 UTC, shukal94 commented on consoleApp/src/main/java/ReadFromConsoleStrategy.java
> +                System.out.println(ex.getMessage());
use logger

2021-11-30 10:26 UTC, shukal94 commented on consoleApp/src/main/java/ReadFromFileStrategy.java
> +    }
remove this method from interface. you can use name field for each command. just define AbstractCommand class and make it implement Command interface

2021-11-30 10:29 UTC, igorchupin commented on consoleApp/src/main/java/CommandTop.java
> +        System.out.println(listAllVariables.subList(0, 5).toString() + "\n");
The logger was added.

2021-11-30 10:32 UTC, igorchupin commented on consoleApp/src/main/java/ICommand.java
> +    }
This was moved to a separate class

2021-11-30 10:33 UTC, igorchupin commented on consoleApp/src/main/java/Marsh.java
> +            jaxbMarshaller.marshal(compar, file ); */
This code, this class was removed.

2021-11-30 10:34 UTC, igorchupin commented on consoleApp/src/main/java/Marsh.java
> +    public class Marsh {
Еhis class was removed.

2021-11-30 10:34 UTC, igorchupin commented on consoleApp/src/main/java/Marsh.java
> +    public class Marsh {
This code, this class was removed.

2021-11-30 10:34 UTC, igorchupin commented on consoleApp/src/main/java/Marsh.java
> +        }
This code, this class was removed.

2021-11-30 10:35 UTC, igorchupin commented on consoleApp/src/main/resources/logs.log
> +2021-11-27 14:21:54,957 INFO logger [main]  Command was executed: CommandError@2c1b9e4b
ignored

2021-11-30 10:51 UTC, igorchupin commented on logs/log4j2.log
> +2021-11-27 14:07:46,750 INFO logger [main] 2021-11-27T14:07:46.750915900 Command was executed: CommandError@4fe89c24
ignored

2021-11-30 10:55 UTC, igorchupin commented on store/pom.xml
> +        </dependency>
This was deleted

2021-11-30 10:55 UTC, igorchupin commented on store/src/main/java/ProductVariable.java
> +        final ArrayList<Comparator> comparatorsList = CommandSort.createComparatorsList();
This was changed

2021-11-30 10:55 UTC, igorchupin commented on store/src/main/resources/configMarsh1.xml
> +</comparators>
Wrapped

2021-11-30 11:02 UTC, igorchupin commented on consoleApp/src/main/java/ICommand.java
> +                    exCommand = new CommandError();
this was changed

2021-11-30 11:02 UTC, igorchupin commented on consoleApp/src/main/java/Marsh.java
> +    public class Marsh {
THis class was removed

2021-11-30 11:06 UTC, igorchupin commented on consoleApp/src/main/java/ReadFromConsoleStrategy.java
> +                try {
Done

2021-11-30 11:14 UTC, igorchupin commented on consoleApp/src/main/java/ReadFromConsoleStrategy.java
> +                System.out.println(ex.getMessage());
It uses logger

2021-11-30 14:18 UTC, shukal94 requested changes

2021-11-30 14:18 UTC, shukal94 commented on consoleApp/src/main/java/Commands/CommandHistory.java
> +    private static final Logger log = LogManager.getLogger("CommandHistory");
getLogger("CommandHistory") - update to getLogger(CommandHistory.class)

2021-11-30 14:18 UTC, shukal94 commented on consoleApp/src/main/java/Commands/CommandQuit.java
> +        ReadFromConsole.closeReader();
why static?

2021-11-30 14:18 UTC, shukal94 commented on consoleApp/src/main/java/Commands/CommandSort.java
> +    static ArrayList<ProductVariable> listAllVariables = new ArrayList<>();
why static?

2021-11-30 14:18 UTC, shukal94 commented on consoleApp/src/main/java/Commands/CommandSort.java
> +public class CommandSort implements ICommand {
do not see AbstractCommand inheritance

2021-11-30 14:18 UTC, shukal94 commented on consoleApp/src/main/java/Commands/CommandQuit.java
> +public class CommandQuit implements ICommand {
do not see AbstractCommand inheritance

2021-11-30 14:18 UTC, shukal94 commented on consoleApp/src/main/java/Commands/CommandTop.java
> +    private static final Logger log = LogManager.getLogger("CommandTop");
static final means constant. rename this field correspondingly

2021-11-30 14:18 UTC, shukal94 commented on consoleApp/src/main/java/Commands/CommandTop.java
> +    private static ArrayList<ProductVariable> listAllVariables = new ArrayList<>();
why static

2021-11-30 14:18 UTC, shukal94 commented on consoleApp/src/main/java/Commands/CreateComparatorsList.java
> +public class CreateComparatorsList {
follow class name convention

2021-11-30 14:18 UTC, shukal94 commented on consoleApp/src/main/java/Commands/CreateComparatorsList.java
> +    public static ArrayList<Comparator> createComparatorsList() {
why don't you use List<Comparator> as type?

2021-11-30 14:18 UTC, shukal94 commented on consoleApp/src/main/java/Commands/FindCommand.java
> +                } catch (NoSuchCommandException ex) {
this operation makes no sense

2021-11-30 14:18 UTC, shukal94 commented on consoleApp/src/main/java/Commands/FindCommand.java
> +        } catch (NullPointerException ex) {
what are you supposed to do with null? how can it be trown while push?

2021-11-30 14:18 UTC, shukal94 commented on consoleApp/src/main/java/Marshaller/ComparatorFromXML.java
> +public class ComparatorFromXML {
if root element's name is comparator class name should be also Comparator

2021-11-30 14:18 UTC, shukal94 commented on consoleApp/src/main/java/Marshaller/ComparatorsFromXML.java
> +public class ComparatorsFromXML {
see above

2021-11-30 14:18 UTC, shukal94 commented on consoleApp/src/main/java/Marshaller/ReadComparatorsList.java
> +    private static final String filePath = "store/src/main/resources/configMarsh1.xml";
what is marsh?

2021-11-30 14:18 UTC, shukal94 commented on consoleApp/src/main/java/Marshaller/ReadComparatorsList.java
> +        System.out.println(comparatorsFromXML.getComparators());
please use logger

2021-11-30 14:18 UTC, shukal94 commented on consoleApp/src/main/java/ReadCommands/ReadFromConsole.java
> +public class ReadFromConsole {
follow class name conventions

2021-11-30 14:18 UTC, shukal94 commented on consoleApp/src/main/java/ReadCommands/ReadFromConsole.java
> +            } catch (NullPointerException ex) {
what you are supposed to do with npe?

2021-11-30 14:18 UTC, shukal94 commented on consoleApp/src/main/java/StoreApp.java
> +        strategy.readAndRunCommand();
read and run?

2021-11-30 14:18 UTC, shukal94 commented on store/src/main/java/productsAndCreation/ProductVariable.java
> +        final ArrayList<Comparator> comparatorsList = CreateComparatorsList.createComparatorsList();
why do you need it?

2021-12-01 14:48 UTC, shukal94 requested changes

2021-12-01 14:48 UTC, shukal94 commented on consoleApp/src/main/java/Commands/AbstractCommand.java
> +    public abstract Object execute() throws NoSuchCommandException;
you don't need to implement this method in abstract class, remove it

2021-12-01 14:48 UTC, shukal94 commented on consoleApp/src/main/java/Commands/AbstractCommand.java
> +    }
makes no sense to override this

2021-12-01 14:48 UTC, shukal94 commented on consoleApp/src/main/java/Commands/CommandQuit.java
> +        System.out.println("\n Program finished!");
use logger

2021-12-01 14:48 UTC, shukal94 commented on consoleApp/src/main/java/Commands/CommandSort.java
> +    String name;
you don't need name field, you're already have it in parent

2021-12-01 14:48 UTC, shukal94 commented on consoleApp/src/main/java/Commands/FindCommand.java
> +        HashMap<String, AbstractCommand> commandsMap = new HashMap<>();
use interface as value type

2021-12-01 14:48 UTC, shukal94 commented on consoleApp/src/main/java/Commands/FindCommand.java
> +        if (result == null) {
also you don't handle null-key exception

2021-12-02 11:33 UTC, shukal94 requested changes
you have groupId for each module, so each module should have the same package hierarchy
like `com.coherent.java.training.chupin` and under these package you should define all the classes

also read java code conventions about packages naming

2021-12-02 11:33 UTC, shukal94 commented on consoleApp/src/main/java/Commands/CommandQuit.java
> +        LOG.log(Level.INFO, " Command -Quit- was executed");
duplicated message, remove sout

2021-12-02 11:33 UTC, shukal94 commented on consoleApp/src/main/java/Commands/CommandSort.java
> +        System.out.println(listAllVariables.toString() + "\n");
use logger

2021-12-02 11:33 UTC, shukal94 commented on consoleApp/src/main/java/Commands/CommandSort.java
> +        System.out.println(listAllVariables.toString() + "\n");
also, do we have toString() method in Collections class? if so, you can use `Arrays.toString(listAllVariables.toArray())`

2021-12-02 11:33 UTC, shukal94 commented on consoleApp/src/main/java/Commands/FindCommand.java
> +            } catch (NullPointerException ex) {
how you are supposed to throw NPE while throwing NoSuchCommand?

just use 
```
if (result == null) {
    throw new NoSuchCommandException(String.format("Command %s not found!", commandName));
}
```

2021-12-02 11:33 UTC, shukal94 commented on consoleApp/src/main/java/Marshaller/Comparators.java
> +    public void setComparators(List<Comparator> comparat) {
comparator

2021-12-02 11:33 UTC, shukal94 commented on consoleApp/src/main/java/Marshaller/Comparators.java
> +    public void add(Comparator comp) {
comparator

not comp, not comparat, etc.

2021-12-02 11:33 UTC, shukal94 commented on consoleApp/src/main/java/Marshaller/CreateComparatorsList.java
> +        LOG.log(Level.INFO, "Method createComparatorsList was executed Result: \n");
what result?

2021-12-02 11:33 UTC, shukal94 commented on consoleApp/src/main/java/Marshaller/ReadComparatorsList.java
> +    private static final Logger LOG = LogManager.getLogger("ReadComparatorsList.class");
not string
you can pass Class<?> variable there, use it
loggers usually use full class name

2021-12-02 11:33 UTC, shukal94 commented on consoleApp/src/main/java/ReadFromConsole/ReadFromConsole.java
> +                LOG.log(Level.ERROR, " NoSuchCommandException was thrown");
no need to catch there

2021-12-02 11:33 UTC, shukal94 commented on consoleApp/src/main/java/ReadFromConsole/ReadFromConsole.java
> +                LOG.log(Level.ERROR, " IOException was thrown");
printStackTrace() already have info about actual exception, no need to add extralog

2021-12-06 09:02 UTC, shukal94 approved these changes

2021-12-06 17:41 UTC, merged